version: "3"

services:
  sqlite-container:
    image: alpine:latest
    volumes:
      - ./database:/data
    container_name: sqlite-container

  sqlitebrowser:
    image: linuxserver/sqlitebrowser
    ports:
      - "3000:3000"
    depends_on:
      - sqlite-container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ENABLE_UWSGI=true
    volumes:
      - ../forge.db:/data/db
    container_name: sqlitebrowser

volumes:
  sqlite_data:
    external: true
