"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from phab_tool.gitea_api.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from phab_tool.gitea_api.exceptions import ApiAttributeError



class BranchProtection(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'approvals_whitelist_teams': ([str],),  # noqa: E501
            'approvals_whitelist_username': ([str],),  # noqa: E501
            'block_on_official_review_requests': (bool,),  # noqa: E501
            'block_on_outdated_branch': (bool,),  # noqa: E501
            'block_on_rejected_reviews': (bool,),  # noqa: E501
            'branch_name': (str,),  # noqa: E501
            'created_at': (datetime,),  # noqa: E501
            'dismiss_stale_approvals': (bool,),  # noqa: E501
            'enable_approvals_whitelist': (bool,),  # noqa: E501
            'enable_merge_whitelist': (bool,),  # noqa: E501
            'enable_push': (bool,),  # noqa: E501
            'enable_push_whitelist': (bool,),  # noqa: E501
            'enable_status_check': (bool,),  # noqa: E501
            'merge_whitelist_teams': ([str],),  # noqa: E501
            'merge_whitelist_usernames': ([str],),  # noqa: E501
            'protected_file_patterns': (str,),  # noqa: E501
            'push_whitelist_deploy_keys': (bool,),  # noqa: E501
            'push_whitelist_teams': ([str],),  # noqa: E501
            'push_whitelist_usernames': ([str],),  # noqa: E501
            'require_signed_commits': (bool,),  # noqa: E501
            'required_approvals': (int,),  # noqa: E501
            'rule_name': (str,),  # noqa: E501
            'status_check_contexts': ([str],),  # noqa: E501
            'unprotected_file_patterns': (str,),  # noqa: E501
            'updated_at': (datetime,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'approvals_whitelist_teams': 'approvals_whitelist_teams',  # noqa: E501
        'approvals_whitelist_username': 'approvals_whitelist_username',  # noqa: E501
        'block_on_official_review_requests': 'block_on_official_review_requests',  # noqa: E501
        'block_on_outdated_branch': 'block_on_outdated_branch',  # noqa: E501
        'block_on_rejected_reviews': 'block_on_rejected_reviews',  # noqa: E501
        'branch_name': 'branch_name',  # noqa: E501
        'created_at': 'created_at',  # noqa: E501
        'dismiss_stale_approvals': 'dismiss_stale_approvals',  # noqa: E501
        'enable_approvals_whitelist': 'enable_approvals_whitelist',  # noqa: E501
        'enable_merge_whitelist': 'enable_merge_whitelist',  # noqa: E501
        'enable_push': 'enable_push',  # noqa: E501
        'enable_push_whitelist': 'enable_push_whitelist',  # noqa: E501
        'enable_status_check': 'enable_status_check',  # noqa: E501
        'merge_whitelist_teams': 'merge_whitelist_teams',  # noqa: E501
        'merge_whitelist_usernames': 'merge_whitelist_usernames',  # noqa: E501
        'protected_file_patterns': 'protected_file_patterns',  # noqa: E501
        'push_whitelist_deploy_keys': 'push_whitelist_deploy_keys',  # noqa: E501
        'push_whitelist_teams': 'push_whitelist_teams',  # noqa: E501
        'push_whitelist_usernames': 'push_whitelist_usernames',  # noqa: E501
        'require_signed_commits': 'require_signed_commits',  # noqa: E501
        'required_approvals': 'required_approvals',  # noqa: E501
        'rule_name': 'rule_name',  # noqa: E501
        'status_check_contexts': 'status_check_contexts',  # noqa: E501
        'unprotected_file_patterns': 'unprotected_file_patterns',  # noqa: E501
        'updated_at': 'updated_at',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """BranchProtection - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            approvals_whitelist_teams ([str]): [optional]  # noqa: E501
            approvals_whitelist_username ([str]): [optional]  # noqa: E501
            block_on_official_review_requests (bool): [optional]  # noqa: E501
            block_on_outdated_branch (bool): [optional]  # noqa: E501
            block_on_rejected_reviews (bool): [optional]  # noqa: E501
            branch_name (str): Deprecated: true. [optional]  # noqa: E501
            created_at (datetime): [optional]  # noqa: E501
            dismiss_stale_approvals (bool): [optional]  # noqa: E501
            enable_approvals_whitelist (bool): [optional]  # noqa: E501
            enable_merge_whitelist (bool): [optional]  # noqa: E501
            enable_push (bool): [optional]  # noqa: E501
            enable_push_whitelist (bool): [optional]  # noqa: E501
            enable_status_check (bool): [optional]  # noqa: E501
            merge_whitelist_teams ([str]): [optional]  # noqa: E501
            merge_whitelist_usernames ([str]): [optional]  # noqa: E501
            protected_file_patterns (str): [optional]  # noqa: E501
            push_whitelist_deploy_keys (bool): [optional]  # noqa: E501
            push_whitelist_teams ([str]): [optional]  # noqa: E501
            push_whitelist_usernames ([str]): [optional]  # noqa: E501
            require_signed_commits (bool): [optional]  # noqa: E501
            required_approvals (int): [optional]  # noqa: E501
            rule_name (str): [optional]  # noqa: E501
            status_check_contexts ([str]): [optional]  # noqa: E501
            unprotected_file_patterns (str): [optional]  # noqa: E501
            updated_at (datetime): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """BranchProtection - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            approvals_whitelist_teams ([str]): [optional]  # noqa: E501
            approvals_whitelist_username ([str]): [optional]  # noqa: E501
            block_on_official_review_requests (bool): [optional]  # noqa: E501
            block_on_outdated_branch (bool): [optional]  # noqa: E501
            block_on_rejected_reviews (bool): [optional]  # noqa: E501
            branch_name (str): Deprecated: true. [optional]  # noqa: E501
            created_at (datetime): [optional]  # noqa: E501
            dismiss_stale_approvals (bool): [optional]  # noqa: E501
            enable_approvals_whitelist (bool): [optional]  # noqa: E501
            enable_merge_whitelist (bool): [optional]  # noqa: E501
            enable_push (bool): [optional]  # noqa: E501
            enable_push_whitelist (bool): [optional]  # noqa: E501
            enable_status_check (bool): [optional]  # noqa: E501
            merge_whitelist_teams ([str]): [optional]  # noqa: E501
            merge_whitelist_usernames ([str]): [optional]  # noqa: E501
            protected_file_patterns (str): [optional]  # noqa: E501
            push_whitelist_deploy_keys (bool): [optional]  # noqa: E501
            push_whitelist_teams ([str]): [optional]  # noqa: E501
            push_whitelist_usernames ([str]): [optional]  # noqa: E501
            require_signed_commits (bool): [optional]  # noqa: E501
            required_approvals (int): [optional]  # noqa: E501
            rule_name (str): [optional]  # noqa: E501
            status_check_contexts ([str]): [optional]  # noqa: E501
            unprotected_file_patterns (str): [optional]  # noqa: E501
            updated_at (datetime): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
