"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from phab_tool.gitea_api.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from phab_tool.gitea_api.exceptions import ApiAttributeError


def lazy_import():
    from phab_tool.gitea_api.model.external_tracker import ExternalTracker
    from phab_tool.gitea_api.model.external_wiki import ExternalWiki
    from phab_tool.gitea_api.model.internal_tracker import InternalTracker
    from phab_tool.gitea_api.model.permission import Permission
    from phab_tool.gitea_api.model.repo_transfer import RepoTransfer
    from phab_tool.gitea_api.model.user import User
    globals()['ExternalTracker'] = ExternalTracker
    globals()['ExternalWiki'] = ExternalWiki
    globals()['InternalTracker'] = InternalTracker
    globals()['Permission'] = Permission
    globals()['RepoTransfer'] = RepoTransfer
    globals()['User'] = User


class Repository(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'allow_merge_commits': (bool,),  # noqa: E501
            'allow_rebase': (bool,),  # noqa: E501
            'allow_rebase_explicit': (bool,),  # noqa: E501
            'allow_rebase_update': (bool,),  # noqa: E501
            'allow_squash_merge': (bool,),  # noqa: E501
            'archived': (bool,),  # noqa: E501
            'avatar_url': (str,),  # noqa: E501
            'clone_url': (str,),  # noqa: E501
            'created_at': (datetime,),  # noqa: E501
            'default_branch': (str,),  # noqa: E501
            'default_delete_branch_after_merge': (bool,),  # noqa: E501
            'default_merge_style': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'empty': (bool,),  # noqa: E501
            'external_tracker': (ExternalTracker,),  # noqa: E501
            'external_wiki': (ExternalWiki,),  # noqa: E501
            'fork': (bool,),  # noqa: E501
            'forks_count': (int,),  # noqa: E501
            'full_name': (str,),  # noqa: E501
            'has_issues': (bool,),  # noqa: E501
            'has_projects': (bool,),  # noqa: E501
            'has_pull_requests': (bool,),  # noqa: E501
            'has_wiki': (bool,),  # noqa: E501
            'html_url': (str,),  # noqa: E501
            'id': (int,),  # noqa: E501
            'ignore_whitespace_conflicts': (bool,),  # noqa: E501
            'internal': (bool,),  # noqa: E501
            'internal_tracker': (InternalTracker,),  # noqa: E501
            'language': (str,),  # noqa: E501
            'languages_url': (str,),  # noqa: E501
            'mirror': (bool,),  # noqa: E501
            'mirror_interval': (str,),  # noqa: E501
            'mirror_updated': (datetime,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'open_issues_count': (int,),  # noqa: E501
            'open_pr_counter': (int,),  # noqa: E501
            'original_url': (str,),  # noqa: E501
            'owner': (User,),  # noqa: E501
            'parent': (Repository,),  # noqa: E501
            'permissions': (Permission,),  # noqa: E501
            'private': (bool,),  # noqa: E501
            'release_counter': (int,),  # noqa: E501
            'repo_transfer': (RepoTransfer,),  # noqa: E501
            'size': (int,),  # noqa: E501
            'ssh_url': (str,),  # noqa: E501
            'stars_count': (int,),  # noqa: E501
            'template': (bool,),  # noqa: E501
            'updated_at': (datetime,),  # noqa: E501
            'watchers_count': (int,),  # noqa: E501
            'website': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'allow_merge_commits': 'allow_merge_commits',  # noqa: E501
        'allow_rebase': 'allow_rebase',  # noqa: E501
        'allow_rebase_explicit': 'allow_rebase_explicit',  # noqa: E501
        'allow_rebase_update': 'allow_rebase_update',  # noqa: E501
        'allow_squash_merge': 'allow_squash_merge',  # noqa: E501
        'archived': 'archived',  # noqa: E501
        'avatar_url': 'avatar_url',  # noqa: E501
        'clone_url': 'clone_url',  # noqa: E501
        'created_at': 'created_at',  # noqa: E501
        'default_branch': 'default_branch',  # noqa: E501
        'default_delete_branch_after_merge': 'default_delete_branch_after_merge',  # noqa: E501
        'default_merge_style': 'default_merge_style',  # noqa: E501
        'description': 'description',  # noqa: E501
        'empty': 'empty',  # noqa: E501
        'external_tracker': 'external_tracker',  # noqa: E501
        'external_wiki': 'external_wiki',  # noqa: E501
        'fork': 'fork',  # noqa: E501
        'forks_count': 'forks_count',  # noqa: E501
        'full_name': 'full_name',  # noqa: E501
        'has_issues': 'has_issues',  # noqa: E501
        'has_projects': 'has_projects',  # noqa: E501
        'has_pull_requests': 'has_pull_requests',  # noqa: E501
        'has_wiki': 'has_wiki',  # noqa: E501
        'html_url': 'html_url',  # noqa: E501
        'id': 'id',  # noqa: E501
        'ignore_whitespace_conflicts': 'ignore_whitespace_conflicts',  # noqa: E501
        'internal': 'internal',  # noqa: E501
        'internal_tracker': 'internal_tracker',  # noqa: E501
        'language': 'language',  # noqa: E501
        'languages_url': 'languages_url',  # noqa: E501
        'mirror': 'mirror',  # noqa: E501
        'mirror_interval': 'mirror_interval',  # noqa: E501
        'mirror_updated': 'mirror_updated',  # noqa: E501
        'name': 'name',  # noqa: E501
        'open_issues_count': 'open_issues_count',  # noqa: E501
        'open_pr_counter': 'open_pr_counter',  # noqa: E501
        'original_url': 'original_url',  # noqa: E501
        'owner': 'owner',  # noqa: E501
        'parent': 'parent',  # noqa: E501
        'permissions': 'permissions',  # noqa: E501
        'private': 'private',  # noqa: E501
        'release_counter': 'release_counter',  # noqa: E501
        'repo_transfer': 'repo_transfer',  # noqa: E501
        'size': 'size',  # noqa: E501
        'ssh_url': 'ssh_url',  # noqa: E501
        'stars_count': 'stars_count',  # noqa: E501
        'template': 'template',  # noqa: E501
        'updated_at': 'updated_at',  # noqa: E501
        'watchers_count': 'watchers_count',  # noqa: E501
        'website': 'website',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Repository - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            allow_merge_commits (bool): [optional]  # noqa: E501
            allow_rebase (bool): [optional]  # noqa: E501
            allow_rebase_explicit (bool): [optional]  # noqa: E501
            allow_rebase_update (bool): [optional]  # noqa: E501
            allow_squash_merge (bool): [optional]  # noqa: E501
            archived (bool): [optional]  # noqa: E501
            avatar_url (str): [optional]  # noqa: E501
            clone_url (str): [optional]  # noqa: E501
            created_at (datetime): [optional]  # noqa: E501
            default_branch (str): [optional]  # noqa: E501
            default_delete_branch_after_merge (bool): [optional]  # noqa: E501
            default_merge_style (str): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            empty (bool): [optional]  # noqa: E501
            external_tracker (ExternalTracker): [optional]  # noqa: E501
            external_wiki (ExternalWiki): [optional]  # noqa: E501
            fork (bool): [optional]  # noqa: E501
            forks_count (int): [optional]  # noqa: E501
            full_name (str): [optional]  # noqa: E501
            has_issues (bool): [optional]  # noqa: E501
            has_projects (bool): [optional]  # noqa: E501
            has_pull_requests (bool): [optional]  # noqa: E501
            has_wiki (bool): [optional]  # noqa: E501
            html_url (str): [optional]  # noqa: E501
            id (int): [optional]  # noqa: E501
            ignore_whitespace_conflicts (bool): [optional]  # noqa: E501
            internal (bool): [optional]  # noqa: E501
            internal_tracker (InternalTracker): [optional]  # noqa: E501
            language (str): [optional]  # noqa: E501
            languages_url (str): [optional]  # noqa: E501
            mirror (bool): [optional]  # noqa: E501
            mirror_interval (str): [optional]  # noqa: E501
            mirror_updated (datetime): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            open_issues_count (int): [optional]  # noqa: E501
            open_pr_counter (int): [optional]  # noqa: E501
            original_url (str): [optional]  # noqa: E501
            owner (User): [optional]  # noqa: E501
            parent (Repository): [optional]  # noqa: E501
            permissions (Permission): [optional]  # noqa: E501
            private (bool): [optional]  # noqa: E501
            release_counter (int): [optional]  # noqa: E501
            repo_transfer (RepoTransfer): [optional]  # noqa: E501
            size (int): [optional]  # noqa: E501
            ssh_url (str): [optional]  # noqa: E501
            stars_count (int): [optional]  # noqa: E501
            template (bool): [optional]  # noqa: E501
            updated_at (datetime): [optional]  # noqa: E501
            watchers_count (int): [optional]  # noqa: E501
            website (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Repository - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            allow_merge_commits (bool): [optional]  # noqa: E501
            allow_rebase (bool): [optional]  # noqa: E501
            allow_rebase_explicit (bool): [optional]  # noqa: E501
            allow_rebase_update (bool): [optional]  # noqa: E501
            allow_squash_merge (bool): [optional]  # noqa: E501
            archived (bool): [optional]  # noqa: E501
            avatar_url (str): [optional]  # noqa: E501
            clone_url (str): [optional]  # noqa: E501
            created_at (datetime): [optional]  # noqa: E501
            default_branch (str): [optional]  # noqa: E501
            default_delete_branch_after_merge (bool): [optional]  # noqa: E501
            default_merge_style (str): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            empty (bool): [optional]  # noqa: E501
            external_tracker (ExternalTracker): [optional]  # noqa: E501
            external_wiki (ExternalWiki): [optional]  # noqa: E501
            fork (bool): [optional]  # noqa: E501
            forks_count (int): [optional]  # noqa: E501
            full_name (str): [optional]  # noqa: E501
            has_issues (bool): [optional]  # noqa: E501
            has_projects (bool): [optional]  # noqa: E501
            has_pull_requests (bool): [optional]  # noqa: E501
            has_wiki (bool): [optional]  # noqa: E501
            html_url (str): [optional]  # noqa: E501
            id (int): [optional]  # noqa: E501
            ignore_whitespace_conflicts (bool): [optional]  # noqa: E501
            internal (bool): [optional]  # noqa: E501
            internal_tracker (InternalTracker): [optional]  # noqa: E501
            language (str): [optional]  # noqa: E501
            languages_url (str): [optional]  # noqa: E501
            mirror (bool): [optional]  # noqa: E501
            mirror_interval (str): [optional]  # noqa: E501
            mirror_updated (datetime): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            open_issues_count (int): [optional]  # noqa: E501
            open_pr_counter (int): [optional]  # noqa: E501
            original_url (str): [optional]  # noqa: E501
            owner (User): [optional]  # noqa: E501
            parent (Repository): [optional]  # noqa: E501
            permissions (Permission): [optional]  # noqa: E501
            private (bool): [optional]  # noqa: E501
            release_counter (int): [optional]  # noqa: E501
            repo_transfer (RepoTransfer): [optional]  # noqa: E501
            size (int): [optional]  # noqa: E501
            ssh_url (str): [optional]  # noqa: E501
            stars_count (int): [optional]  # noqa: E501
            template (bool): [optional]  # noqa: E501
            updated_at (datetime): [optional]  # noqa: E501
            watchers_count (int): [optional]  # noqa: E501
            website (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
