"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from phab_tool.gitea_api.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from phab_tool.gitea_api.exceptions import ApiAttributeError


def lazy_import():
    from phab_tool.gitea_api.model.comment import Comment
    from phab_tool.gitea_api.model.issue import Issue
    from phab_tool.gitea_api.model.label import Label
    from phab_tool.gitea_api.model.milestone import Milestone
    from phab_tool.gitea_api.model.team import Team
    from phab_tool.gitea_api.model.tracked_time import TrackedTime
    from phab_tool.gitea_api.model.user import User
    globals()['Comment'] = Comment
    globals()['Issue'] = Issue
    globals()['Label'] = Label
    globals()['Milestone'] = Milestone
    globals()['Team'] = Team
    globals()['TrackedTime'] = TrackedTime
    globals()['User'] = User


class TimelineComment(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'assignee': (User,),  # noqa: E501
            'assignee_team': (Team,),  # noqa: E501
            'body': (str,),  # noqa: E501
            'created_at': (datetime,),  # noqa: E501
            'dependent_issue': (Issue,),  # noqa: E501
            'html_url': (str,),  # noqa: E501
            'id': (int,),  # noqa: E501
            'issue_url': (str,),  # noqa: E501
            'label': (Label,),  # noqa: E501
            'milestone': (Milestone,),  # noqa: E501
            'new_ref': (str,),  # noqa: E501
            'new_title': (str,),  # noqa: E501
            'old_milestone': (Milestone,),  # noqa: E501
            'old_project_id': (int,),  # noqa: E501
            'old_ref': (str,),  # noqa: E501
            'old_title': (str,),  # noqa: E501
            'project_id': (int,),  # noqa: E501
            'pull_request_url': (str,),  # noqa: E501
            'ref_action': (str,),  # noqa: E501
            'ref_comment': (Comment,),  # noqa: E501
            'ref_commit_sha': (str,),  # noqa: E501
            'ref_issue': (Issue,),  # noqa: E501
            'removed_assignee': (bool,),  # noqa: E501
            'resolve_doer': (User,),  # noqa: E501
            'review_id': (int,),  # noqa: E501
            'tracked_time': (TrackedTime,),  # noqa: E501
            'type': (str,),  # noqa: E501
            'updated_at': (datetime,),  # noqa: E501
            'user': (User,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'assignee': 'assignee',  # noqa: E501
        'assignee_team': 'assignee_team',  # noqa: E501
        'body': 'body',  # noqa: E501
        'created_at': 'created_at',  # noqa: E501
        'dependent_issue': 'dependent_issue',  # noqa: E501
        'html_url': 'html_url',  # noqa: E501
        'id': 'id',  # noqa: E501
        'issue_url': 'issue_url',  # noqa: E501
        'label': 'label',  # noqa: E501
        'milestone': 'milestone',  # noqa: E501
        'new_ref': 'new_ref',  # noqa: E501
        'new_title': 'new_title',  # noqa: E501
        'old_milestone': 'old_milestone',  # noqa: E501
        'old_project_id': 'old_project_id',  # noqa: E501
        'old_ref': 'old_ref',  # noqa: E501
        'old_title': 'old_title',  # noqa: E501
        'project_id': 'project_id',  # noqa: E501
        'pull_request_url': 'pull_request_url',  # noqa: E501
        'ref_action': 'ref_action',  # noqa: E501
        'ref_comment': 'ref_comment',  # noqa: E501
        'ref_commit_sha': 'ref_commit_sha',  # noqa: E501
        'ref_issue': 'ref_issue',  # noqa: E501
        'removed_assignee': 'removed_assignee',  # noqa: E501
        'resolve_doer': 'resolve_doer',  # noqa: E501
        'review_id': 'review_id',  # noqa: E501
        'tracked_time': 'tracked_time',  # noqa: E501
        'type': 'type',  # noqa: E501
        'updated_at': 'updated_at',  # noqa: E501
        'user': 'user',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """TimelineComment - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            assignee (User): [optional]  # noqa: E501
            assignee_team (Team): [optional]  # noqa: E501
            body (str): [optional]  # noqa: E501
            created_at (datetime): [optional]  # noqa: E501
            dependent_issue (Issue): [optional]  # noqa: E501
            html_url (str): [optional]  # noqa: E501
            id (int): [optional]  # noqa: E501
            issue_url (str): [optional]  # noqa: E501
            label (Label): [optional]  # noqa: E501
            milestone (Milestone): [optional]  # noqa: E501
            new_ref (str): [optional]  # noqa: E501
            new_title (str): [optional]  # noqa: E501
            old_milestone (Milestone): [optional]  # noqa: E501
            old_project_id (int): [optional]  # noqa: E501
            old_ref (str): [optional]  # noqa: E501
            old_title (str): [optional]  # noqa: E501
            project_id (int): [optional]  # noqa: E501
            pull_request_url (str): [optional]  # noqa: E501
            ref_action (str): [optional]  # noqa: E501
            ref_comment (Comment): [optional]  # noqa: E501
            ref_commit_sha (str): commit SHA where issue/PR was referenced. [optional]  # noqa: E501
            ref_issue (Issue): [optional]  # noqa: E501
            removed_assignee (bool): whether the assignees were removed or added. [optional]  # noqa: E501
            resolve_doer (User): [optional]  # noqa: E501
            review_id (int): [optional]  # noqa: E501
            tracked_time (TrackedTime): [optional]  # noqa: E501
            type (str): [optional]  # noqa: E501
            updated_at (datetime): [optional]  # noqa: E501
            user (User): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """TimelineComment - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            assignee (User): [optional]  # noqa: E501
            assignee_team (Team): [optional]  # noqa: E501
            body (str): [optional]  # noqa: E501
            created_at (datetime): [optional]  # noqa: E501
            dependent_issue (Issue): [optional]  # noqa: E501
            html_url (str): [optional]  # noqa: E501
            id (int): [optional]  # noqa: E501
            issue_url (str): [optional]  # noqa: E501
            label (Label): [optional]  # noqa: E501
            milestone (Milestone): [optional]  # noqa: E501
            new_ref (str): [optional]  # noqa: E501
            new_title (str): [optional]  # noqa: E501
            old_milestone (Milestone): [optional]  # noqa: E501
            old_project_id (int): [optional]  # noqa: E501
            old_ref (str): [optional]  # noqa: E501
            old_title (str): [optional]  # noqa: E501
            project_id (int): [optional]  # noqa: E501
            pull_request_url (str): [optional]  # noqa: E501
            ref_action (str): [optional]  # noqa: E501
            ref_comment (Comment): [optional]  # noqa: E501
            ref_commit_sha (str): commit SHA where issue/PR was referenced. [optional]  # noqa: E501
            ref_issue (Issue): [optional]  # noqa: E501
            removed_assignee (bool): whether the assignees were removed or added. [optional]  # noqa: E501
            resolve_doer (User): [optional]  # noqa: E501
            review_id (int): [optional]  # noqa: E501
            tracked_time (TrackedTime): [optional]  # noqa: E501
            type (str): [optional]  # noqa: E501
            updated_at (datetime): [optional]  # noqa: E501
            user (User): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
