#!/bin/sh
jq 'map(.component) | unique' ./data/bug_data_formatted.json

# [
#   "Advocacy",
#   "Books & Articles",
#   "Bug Tracker",
#   "Code Review",
#   "Core Infrastructure",
#   "FTP/WWW Sites & Mirrors",
#   "Forums",
#   "FreeBSD Update",
#   "Git Integration",
#   "IRC",
#   "Individual Port(s)",
#   "Legal & Compliance",
#   "Mailing Lists",
#   "Manual Pages",
#   "Package Infrastructure",
#   "Ports Framework",
#   "Portscout",
#   "Portsmon",
#   "Portsnap",
#   "Security Team",
#   "Spam",
#   "Testing & CI",
#   "Trash",
#   "Website",
#   "Wiki",
#   "alpha",
#   "amd64",
#   "arm",
#   "bhyve",
#   "bin",
#   "conf",
#   "gnu",
#   "i386",
#   "ia64",
#   "java",
#   "kern",
#   "misc",
#   "powerpc",
#   "riscv",
#   "sparc64",
#   "standards",
#   "tests",
#   "threads",
#   "usb",
#   "wireless"
# ]
