# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from phab_tool.gitea_api.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from phab_tool.gitea_api.model.api_error import APIError
from phab_tool.gitea_api.model.access_token import AccessToken
from phab_tool.gitea_api.model.activity_pub import ActivityPub
from phab_tool.gitea_api.model.add_collaborator_option import AddCollaboratorOption
from phab_tool.gitea_api.model.add_time_option import AddTimeOption
from phab_tool.gitea_api.model.annotated_tag import AnnotatedTag
from phab_tool.gitea_api.model.annotated_tag_object import AnnotatedTagObject
from phab_tool.gitea_api.model.attachment import Attachment
from phab_tool.gitea_api.model.branch import Branch
from phab_tool.gitea_api.model.branch_protection import BranchProtection
from phab_tool.gitea_api.model.changed_file import ChangedFile
from phab_tool.gitea_api.model.combined_status import CombinedStatus
from phab_tool.gitea_api.model.comment import Comment
from phab_tool.gitea_api.model.commit import Commit
from phab_tool.gitea_api.model.commit_affected_files import CommitAffectedFiles
from phab_tool.gitea_api.model.commit_date_options import CommitDateOptions
from phab_tool.gitea_api.model.commit_meta import CommitMeta
from phab_tool.gitea_api.model.commit_stats import CommitStats
from phab_tool.gitea_api.model.commit_status import CommitStatus
from phab_tool.gitea_api.model.commit_user import CommitUser
from phab_tool.gitea_api.model.contents_response import ContentsResponse
from phab_tool.gitea_api.model.create_access_token_option import CreateAccessTokenOption
from phab_tool.gitea_api.model.create_branch_protection_option import CreateBranchProtectionOption
from phab_tool.gitea_api.model.create_branch_repo_option import CreateBranchRepoOption
from phab_tool.gitea_api.model.create_email_option import CreateEmailOption
from phab_tool.gitea_api.model.create_file_options import CreateFileOptions
from phab_tool.gitea_api.model.create_fork_option import CreateForkOption
from phab_tool.gitea_api.model.create_gpg_key_option import CreateGPGKeyOption
from phab_tool.gitea_api.model.create_hook_option import CreateHookOption
from phab_tool.gitea_api.model.create_hook_option_config import CreateHookOptionConfig
from phab_tool.gitea_api.model.create_issue_comment_option import CreateIssueCommentOption
from phab_tool.gitea_api.model.create_issue_option import CreateIssueOption
from phab_tool.gitea_api.model.create_key_option import CreateKeyOption
from phab_tool.gitea_api.model.create_label_option import CreateLabelOption
from phab_tool.gitea_api.model.create_milestone_option import CreateMilestoneOption
from phab_tool.gitea_api.model.create_o_auth2_application_options import CreateOAuth2ApplicationOptions
from phab_tool.gitea_api.model.create_org_option import CreateOrgOption
from phab_tool.gitea_api.model.create_pull_request_option import CreatePullRequestOption
from phab_tool.gitea_api.model.create_pull_review_comment import CreatePullReviewComment
from phab_tool.gitea_api.model.create_pull_review_options import CreatePullReviewOptions
from phab_tool.gitea_api.model.create_push_mirror_option import CreatePushMirrorOption
from phab_tool.gitea_api.model.create_release_option import CreateReleaseOption
from phab_tool.gitea_api.model.create_repo_option import CreateRepoOption
from phab_tool.gitea_api.model.create_status_option import CreateStatusOption
from phab_tool.gitea_api.model.create_tag_option import CreateTagOption
from phab_tool.gitea_api.model.create_team_option import CreateTeamOption
from phab_tool.gitea_api.model.create_user_option import CreateUserOption
from phab_tool.gitea_api.model.create_wiki_page_options import CreateWikiPageOptions
from phab_tool.gitea_api.model.cron import Cron
from phab_tool.gitea_api.model.delete_email_option import DeleteEmailOption
from phab_tool.gitea_api.model.delete_file_options import DeleteFileOptions
from phab_tool.gitea_api.model.deploy_key import DeployKey
from phab_tool.gitea_api.model.dismiss_pull_review_options import DismissPullReviewOptions
from phab_tool.gitea_api.model.edit_attachment_options import EditAttachmentOptions
from phab_tool.gitea_api.model.edit_branch_protection_option import EditBranchProtectionOption
from phab_tool.gitea_api.model.edit_deadline_option import EditDeadlineOption
from phab_tool.gitea_api.model.edit_git_hook_option import EditGitHookOption
from phab_tool.gitea_api.model.edit_hook_option import EditHookOption
from phab_tool.gitea_api.model.edit_issue_comment_option import EditIssueCommentOption
from phab_tool.gitea_api.model.edit_issue_option import EditIssueOption
from phab_tool.gitea_api.model.edit_label_option import EditLabelOption
from phab_tool.gitea_api.model.edit_milestone_option import EditMilestoneOption
from phab_tool.gitea_api.model.edit_org_option import EditOrgOption
from phab_tool.gitea_api.model.edit_pull_request_option import EditPullRequestOption
from phab_tool.gitea_api.model.edit_reaction_option import EditReactionOption
from phab_tool.gitea_api.model.edit_release_option import EditReleaseOption
from phab_tool.gitea_api.model.edit_repo_option import EditRepoOption
from phab_tool.gitea_api.model.edit_team_option import EditTeamOption
from phab_tool.gitea_api.model.edit_user_option import EditUserOption
from phab_tool.gitea_api.model.email import Email
from phab_tool.gitea_api.model.external_tracker import ExternalTracker
from phab_tool.gitea_api.model.external_wiki import ExternalWiki
from phab_tool.gitea_api.model.file_commit_response import FileCommitResponse
from phab_tool.gitea_api.model.file_delete_response import FileDeleteResponse
from phab_tool.gitea_api.model.file_links_response import FileLinksResponse
from phab_tool.gitea_api.model.file_response import FileResponse
from phab_tool.gitea_api.model.gpg_key import GPGKey
from phab_tool.gitea_api.model.gpg_key_email import GPGKeyEmail
from phab_tool.gitea_api.model.general_api_settings import GeneralAPISettings
from phab_tool.gitea_api.model.general_attachment_settings import GeneralAttachmentSettings
from phab_tool.gitea_api.model.general_repo_settings import GeneralRepoSettings
from phab_tool.gitea_api.model.general_ui_settings import GeneralUISettings
from phab_tool.gitea_api.model.generate_repo_option import GenerateRepoOption
from phab_tool.gitea_api.model.git_blob_response import GitBlobResponse
from phab_tool.gitea_api.model.git_entry import GitEntry
from phab_tool.gitea_api.model.git_hook import GitHook
from phab_tool.gitea_api.model.git_object import GitObject
from phab_tool.gitea_api.model.git_tree_response import GitTreeResponse
from phab_tool.gitea_api.model.hook import Hook
from phab_tool.gitea_api.model.identity import Identity
from phab_tool.gitea_api.model.inline_response200 import InlineResponse200
from phab_tool.gitea_api.model.inline_response2001 import InlineResponse2001
from phab_tool.gitea_api.model.internal_tracker import InternalTracker
from phab_tool.gitea_api.model.issue import Issue
from phab_tool.gitea_api.model.issue_deadline import IssueDeadline
from phab_tool.gitea_api.model.issue_form_field import IssueFormField
from phab_tool.gitea_api.model.issue_labels_option import IssueLabelsOption
from phab_tool.gitea_api.model.issue_template import IssueTemplate
from phab_tool.gitea_api.model.issue_template_labels import IssueTemplateLabels
from phab_tool.gitea_api.model.label import Label
from phab_tool.gitea_api.model.markdown_option import MarkdownOption
from phab_tool.gitea_api.model.merge_pull_request_option import MergePullRequestOption
from phab_tool.gitea_api.model.migrate_repo_options import MigrateRepoOptions
from phab_tool.gitea_api.model.milestone import Milestone
from phab_tool.gitea_api.model.node_info import NodeInfo
from phab_tool.gitea_api.model.node_info_services import NodeInfoServices
from phab_tool.gitea_api.model.node_info_software import NodeInfoSoftware
from phab_tool.gitea_api.model.node_info_usage import NodeInfoUsage
from phab_tool.gitea_api.model.node_info_usage_users import NodeInfoUsageUsers
from phab_tool.gitea_api.model.note import Note
from phab_tool.gitea_api.model.notification_count import NotificationCount
from phab_tool.gitea_api.model.notification_subject import NotificationSubject
from phab_tool.gitea_api.model.notification_thread import NotificationThread
from phab_tool.gitea_api.model.o_auth2_application import OAuth2Application
from phab_tool.gitea_api.model.organization import Organization
from phab_tool.gitea_api.model.organization_permissions import OrganizationPermissions
from phab_tool.gitea_api.model.pr_branch_info import PRBranchInfo
from phab_tool.gitea_api.model.package import Package
from phab_tool.gitea_api.model.package_file import PackageFile
from phab_tool.gitea_api.model.payload_commit import PayloadCommit
from phab_tool.gitea_api.model.payload_commit_verification import PayloadCommitVerification
from phab_tool.gitea_api.model.payload_user import PayloadUser
from phab_tool.gitea_api.model.permission import Permission
from phab_tool.gitea_api.model.public_key import PublicKey
from phab_tool.gitea_api.model.pull_request import PullRequest
from phab_tool.gitea_api.model.pull_request_meta import PullRequestMeta
from phab_tool.gitea_api.model.pull_review import PullReview
from phab_tool.gitea_api.model.pull_review_comment import PullReviewComment
from phab_tool.gitea_api.model.pull_review_request_options import PullReviewRequestOptions
from phab_tool.gitea_api.model.push_mirror import PushMirror
from phab_tool.gitea_api.model.reaction import Reaction
from phab_tool.gitea_api.model.reference import Reference
from phab_tool.gitea_api.model.release import Release
from phab_tool.gitea_api.model.repo_collaborator_permission import RepoCollaboratorPermission
from phab_tool.gitea_api.model.repo_commit import RepoCommit
from phab_tool.gitea_api.model.repo_topic_options import RepoTopicOptions
from phab_tool.gitea_api.model.repo_transfer import RepoTransfer
from phab_tool.gitea_api.model.repository import Repository
from phab_tool.gitea_api.model.repository_meta import RepositoryMeta
from phab_tool.gitea_api.model.search_results import SearchResults
from phab_tool.gitea_api.model.server_version import ServerVersion
from phab_tool.gitea_api.model.stop_watch import StopWatch
from phab_tool.gitea_api.model.submit_pull_review_options import SubmitPullReviewOptions
from phab_tool.gitea_api.model.tag import Tag
from phab_tool.gitea_api.model.team import Team
from phab_tool.gitea_api.model.timeline_comment import TimelineComment
from phab_tool.gitea_api.model.topic_name import TopicName
from phab_tool.gitea_api.model.topic_response import TopicResponse
from phab_tool.gitea_api.model.tracked_time import TrackedTime
from phab_tool.gitea_api.model.transfer_repo_option import TransferRepoOption
from phab_tool.gitea_api.model.update_file_options import UpdateFileOptions
from phab_tool.gitea_api.model.user import User
from phab_tool.gitea_api.model.user_heatmap_data import UserHeatmapData
from phab_tool.gitea_api.model.user_settings import UserSettings
from phab_tool.gitea_api.model.user_settings_options import UserSettingsOptions
from phab_tool.gitea_api.model.watch_info import WatchInfo
from phab_tool.gitea_api.model.wiki_commit import WikiCommit
from phab_tool.gitea_api.model.wiki_commit_list import WikiCommitList
from phab_tool.gitea_api.model.wiki_page import WikiPage
from phab_tool.gitea_api.model.wiki_page_meta_data import WikiPageMetaData
