"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.file_commit_response import FileCommitResponse
from phab_tool.gitea_api.model.payload_commit_verification import PayloadCommitVerification
globals()['FileCommitResponse'] = FileCommitResponse
globals()['PayloadCommitVerification'] = PayloadCommitVerification
from phab_tool.gitea_api.model.file_delete_response import FileDeleteResponse


class TestFileDeleteResponse(unittest.TestCase):
    """FileDeleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileDeleteResponse(self):
        """Test FileDeleteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileDeleteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
