"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.commit_meta import CommitMeta
from phab_tool.gitea_api.model.commit_user import CommitUser
globals()['CommitMeta'] = CommitMeta
globals()['CommitUser'] = CommitUser
from phab_tool.gitea_api.model.file_commit_response import FileCommitResponse


class TestFileCommitResponse(unittest.TestCase):
    """FileCommitResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileCommitResponse(self):
        """Test FileCommitResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileCommitResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
