"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.submit_pull_review_options import SubmitPullReviewOptions


class TestSubmitPullReviewOptions(unittest.TestCase):
    """SubmitPullReviewOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmitPullReviewOptions(self):
        """Test SubmitPullReviewOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubmitPullReviewOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
