"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.repository import Repository
from phab_tool.gitea_api.model.user import User
globals()['Repository'] = Repository
globals()['User'] = User
from phab_tool.gitea_api.model.package import Package


class TestPackage(unittest.TestCase):
    """Package unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackage(self):
        """Test Package"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Package()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
