"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.comment import Comment
from phab_tool.gitea_api.model.issue import Issue
from phab_tool.gitea_api.model.label import Label
from phab_tool.gitea_api.model.milestone import Milestone
from phab_tool.gitea_api.model.team import Team
from phab_tool.gitea_api.model.tracked_time import TrackedTime
from phab_tool.gitea_api.model.user import User
globals()['Comment'] = Comment
globals()['Issue'] = Issue
globals()['Label'] = Label
globals()['Milestone'] = Milestone
globals()['Team'] = Team
globals()['TrackedTime'] = TrackedTime
globals()['User'] = User
from phab_tool.gitea_api.model.timeline_comment import TimelineComment


class TestTimelineComment(unittest.TestCase):
    """TimelineComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimelineComment(self):
        """Test TimelineComment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TimelineComment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
