"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.create_hook_option_config import CreateHookOptionConfig
globals()['CreateHookOptionConfig'] = CreateHookOptionConfig
from phab_tool.gitea_api.model.create_hook_option import CreateHookOption


class TestCreateHookOption(unittest.TestCase):
    """CreateHookOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateHookOption(self):
        """Test CreateHookOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateHookOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
