"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.payload_commit import PayloadCommit
globals()['PayloadCommit'] = PayloadCommit
from phab_tool.gitea_api.model.branch import Branch


class TestBranch(unittest.TestCase):
    """Branch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBranch(self):
        """Test Branch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Branch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
