"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.attachment import Attachment
from phab_tool.gitea_api.model.label import Label
from phab_tool.gitea_api.model.milestone import Milestone
from phab_tool.gitea_api.model.pull_request_meta import PullRequestMeta
from phab_tool.gitea_api.model.repository_meta import RepositoryMeta
from phab_tool.gitea_api.model.user import User
globals()['Attachment'] = Attachment
globals()['Label'] = Label
globals()['Milestone'] = Milestone
globals()['PullRequestMeta'] = PullRequestMeta
globals()['RepositoryMeta'] = RepositoryMeta
globals()['User'] = User
from phab_tool.gitea_api.model.issue import Issue


class TestIssue(unittest.TestCase):
    """Issue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssue(self):
        """Test Issue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Issue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
