"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.git_entry import GitEntry
globals()['GitEntry'] = GitEntry
from phab_tool.gitea_api.model.git_tree_response import GitTreeResponse


class TestGitTreeResponse(unittest.TestCase):
    """GitTreeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGitTreeResponse(self):
        """Test GitTreeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GitTreeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
