"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.notification_subject import NotificationSubject
from phab_tool.gitea_api.model.repository import Repository
globals()['NotificationSubject'] = NotificationSubject
globals()['Repository'] = Repository
from phab_tool.gitea_api.model.notification_thread import NotificationThread


class TestNotificationThread(unittest.TestCase):
    """NotificationThread unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationThread(self):
        """Test NotificationThread"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotificationThread()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
