"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.commit_affected_files import CommitAffectedFiles
from phab_tool.gitea_api.model.commit_meta import CommitMeta
from phab_tool.gitea_api.model.commit_stats import CommitStats
from phab_tool.gitea_api.model.repo_commit import RepoCommit
from phab_tool.gitea_api.model.user import User
globals()['CommitAffectedFiles'] = CommitAffectedFiles
globals()['CommitMeta'] = CommitMeta
globals()['CommitStats'] = CommitStats
globals()['RepoCommit'] = RepoCommit
globals()['User'] = User
from phab_tool.gitea_api.model.commit import Commit


class TestCommit(unittest.TestCase):
    """Commit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommit(self):
        """Test Commit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Commit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
