"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.notification_count import NotificationCount


class TestNotificationCount(unittest.TestCase):
    """NotificationCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationCount(self):
        """Test NotificationCount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotificationCount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
