"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.commit_status import CommitStatus
from phab_tool.gitea_api.model.repository import Repository
globals()['CommitStatus'] = CommitStatus
globals()['Repository'] = Repository
from phab_tool.gitea_api.model.combined_status import CombinedStatus


class TestCombinedStatus(unittest.TestCase):
    """CombinedStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCombinedStatus(self):
        """Test CombinedStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CombinedStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
