"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.api.package_api import PackageApi  # noqa: E501


class TestPackageApi(unittest.TestCase):
    """PackageApi unit test stubs"""

    def setUp(self):
        self.api = PackageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_package(self):
        """Test case for delete_package

        Delete a package  # noqa: E501
        """
        pass

    def test_get_package(self):
        """Test case for get_package

        Gets a package  # noqa: E501
        """
        pass

    def test_list_package_files(self):
        """Test case for list_package_files

        Gets all files of a package  # noqa: E501
        """
        pass

    def test_list_packages(self):
        """Test case for list_packages

        Gets all packages of an owner  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
