"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.commit_meta import CommitMeta
from phab_tool.gitea_api.model.commit_user import CommitUser
from phab_tool.gitea_api.model.payload_commit_verification import PayloadCommitVerification
globals()['CommitMeta'] = CommitMeta
globals()['CommitUser'] = CommitUser
globals()['PayloadCommitVerification'] = PayloadCommitVerification
from phab_tool.gitea_api.model.repo_commit import RepoCommit


class TestRepoCommit(unittest.TestCase):
    """RepoCommit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepoCommit(self):
        """Test RepoCommit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepoCommit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
