"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.create_branch_repo_option import CreateBranchRepoOption


class TestCreateBranchRepoOption(unittest.TestCase):
    """CreateBranchRepoOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateBranchRepoOption(self):
        """Test CreateBranchRepoOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateBranchRepoOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
