"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.attachment import Attachment
from phab_tool.gitea_api.model.user import User
globals()['Attachment'] = Attachment
globals()['User'] = User
from phab_tool.gitea_api.model.release import Release


class TestRelease(unittest.TestCase):
    """Release unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRelease(self):
        """Test Release"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Release()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
