"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.create_user_option import CreateUserOption


class TestCreateUserOption(unittest.TestCase):
    """CreateUserOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateUserOption(self):
        """Test CreateUserOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateUserOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
