"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.team import Team
from phab_tool.gitea_api.model.user import User
globals()['Team'] = Team
globals()['User'] = User
from phab_tool.gitea_api.model.repo_transfer import RepoTransfer


class TestRepoTransfer(unittest.TestCase):
    """RepoTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepoTransfer(self):
        """Test RepoTransfer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepoTransfer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
