"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.node_info_services import NodeInfoServices
from phab_tool.gitea_api.model.node_info_software import NodeInfoSoftware
from phab_tool.gitea_api.model.node_info_usage import NodeInfoUsage
globals()['NodeInfoServices'] = NodeInfoServices
globals()['NodeInfoSoftware'] = NodeInfoSoftware
globals()['NodeInfoUsage'] = NodeInfoUsage
from phab_tool.gitea_api.model.node_info import NodeInfo


class TestNodeInfo(unittest.TestCase):
    """NodeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeInfo(self):
        """Test NodeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NodeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
