"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import phab_tool.gitea_api
from phab_tool.gitea_api.model.gpg_key_email import GPGKeyEmail
globals()['GPGKeyEmail'] = GPGKeyEmail
from phab_tool.gitea_api.model.gpg_key import GPGKey


class TestGPGKey(unittest.TestCase):
    """GPGKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGPGKey(self):
        """Test GPGKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GPGKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
