# flake8: noqa

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.0+dev-367-g8042ec1b9
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0"

# import ApiClient
from phab_tool.gitea_api.api_client import ApiClient

# import Configuration
from phab_tool.gitea_api.configuration import Configuration

# import exceptions
from phab_tool.gitea_api.exceptions import OpenApiException
from phab_tool.gitea_api.exceptions import ApiAttributeError
from phab_tool.gitea_api.exceptions import ApiTypeError
from phab_tool.gitea_api.exceptions import ApiValueError
from phab_tool.gitea_api.exceptions import ApiKeyError
from phab_tool.gitea_api.exceptions import ApiException
